@Library(value='kids-first/aws-infra-jenkins-shared-libraries', changelog=false) _
ecs_service_type_1_standard {
    projectName = "riff"
    agentLabel = "terraform-testing"
    environments = "qa,prd"
    docker_image_type = "alpine"
    entrypoint_command = "/srv/riff/exec/run.sh"
    quick_deploy = "true"
    external_config_repo = "false"
    internal_app         = "false"
    container_port = "8081"
    vcpu_container             = "1024"
    memory_container           = "2048"
    vcpu_task                  = "1024"
    memory_task                = "2048"
    health_check_path = "/swagger-ui.html"
    dependencies = "ecr"
    additional_ssl_cert_domain_name = "*.kidsfirstdrc.org"
    publish_to_public_repo = "true"
    create_additional_internal_alb = "1"
}
